apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-pod1
  name: new-pod1-lab19
  namespace: demo-lab01
spec:
  containers:
  - image: nginx
    name: new-pod1


---
apiVersion: v1
kind: Service
metadata:
  name: rest-simpleapp-svc-lab19
  namespace: demo-lab01
spec:
  type: NodePort
  selector:
    run: new-pod1
  ports:
    - port: 8088
      targetPort: 80 
      nodePort: 32100 
      
